export const styles = {
  componentContainer: {
    width: "100vw",
    height: "100vh",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
  },
  paper: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "30px 20px",
    borderRadius: "4%",
    marginTop: "15vh",
    padding: "3rem",
  },
  formContainer: {
    width: "25vw",
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    gap: "30px 20px",
  },
  button: {
    paddingTop: "0.1em",
    paddingBottom: "0.1em",
    margin: "1rem",
    width: "10vw",
    borderRadius: "37px",
    fontSize: "1.1em",
    borderColor: "black",
    appearance: "none",
    backgroundColor: "transparent",
    border: "2px solid #1A1A1A",
    boxSizing: "border-box",
    color: "white",
    cursor: "pointer",
    display: "inline-block",
    fontWeight: "600",
    lineHeight: "normal",
    minHeight: "60px",
    minWidth: "0",
    outline: "none",
    textAlign: "center",
    textDecoration: "none",
    transition: "all 300ms cubic-bezier(.23, 1, 0.32, 1)",
    userSelect: "none",
    touchAction: "manipulation",
    willChange: "transform",
    "&.MuiTextField-root:hover": {
      color: "#fff",
      backgroundColor: "#1A1A1A",
      boxShadow: "rgba(0, 0, 0, 0.25) 0 8px 15px",
      transform: "translateY(-2px)",
    },
    "&.MuiTextField-root:active": {
      boxShadow: "none",
      transform: "translateY(0)",
    },
    "&.MuiTextField-root:disabled": {
      pointerEvents: "none",
    },
  },
  textField: {
    width: "20vw",
  },
  typography: {
    fontSize: "3em",
    fontWeight: "bold",
    marginBottom: "0.5em",
  },
};
